server:
  port: 9181
  context-path: /
  max-http-header-size: 4048576
  tomcat:
    max-http-post-size: 1000MB  #请求参数长度
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://115.29.166.64:3306/certification-jg-8081?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password: yjzky
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

  # spring boot
  application:
    name: jinfang-graduatio-project

  # file upload max size 20M
  servlet:
        multipart:
          max-file-size: 20971520     # 文件上传大小限制为20M
          max-request-size: 20971520  # 请求大小限制为20M

storage:
  disk: D:\upload\graduation-application-9181\
  domain: http://localhost/pdf/
  zip: D:\template\graduation-application-9181\

template:
  source: D:\template\graduation-application\template-9181
  target: D:\template\graduation-application\template-9181\target

logback:
    logdir: D:\logs\graduation-application-9181-log

  #打印sql
logging.level.com.jinfang.graduationproject.mapper: debug